<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Session', 'doctrine-session');

/**
 * BaseSession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $sid
 * @property string $sdata
 * @property integer $stime
 * 
 * @method string  getSid()   Returns the current record's "sid" value
 * @method string  getSdata() Returns the current record's "sdata" value
 * @method integer getStime() Returns the current record's "stime" value
 * @method Session setSid()   Sets the current record's "sid" value
 * @method Session setSdata() Sets the current record's "sdata" value
 * @method Session setStime() Sets the current record's "stime" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSession extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('session');
        $this->hasColumn('sid', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 32,
             ));
        $this->hasColumn('sdata', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('stime', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}