<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FishForGroup', 'doctrine-discuss');

/**
 * BaseFishForGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pid
 * @property integer $fish_id
 * @property Doctrine_Collection $UserGroup
 * @property Doctrine_Collection $Fish
 * 
 * @method integer             getPid()       Returns the current record's "pid" value
 * @method integer             getFishId()    Returns the current record's "fish_id" value
 * @method Doctrine_Collection getUserGroup() Returns the current record's "UserGroup" collection
 * @method Doctrine_Collection getFish()      Returns the current record's "Fish" collection
 * @method FishForGroup        setPid()       Sets the current record's "pid" value
 * @method FishForGroup        setFishId()    Sets the current record's "fish_id" value
 * @method FishForGroup        setUserGroup() Sets the current record's "UserGroup" collection
 * @method FishForGroup        setFish()      Sets the current record's "Fish" collection
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFishForGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fish_for_group');
        $this->hasColumn('pid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fish_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserGroup', array(
             'local' => 'pid',
             'foreign' => 'id'));

        $this->hasMany('Fish', array(
             'local' => 'fish_id',
             'foreign' => 'id'));
    }
}