<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Blog', 'doctrine-discuss');

/**
 * BaseBlog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property decimal $lat
 * @property decimal $lon
 * @property timestamp $date_create
 * @property timestamp $ts
 * @property string $content
 * @property string $loc
 * @property integer $user_id
 * @property string $caption
 * @property string $keyword
 * @property timestamp $date_blog
 * @property integer $sec
 * @property integer $group_id
 * @property string $url
 * @property string $url_caption
 * @property FileForBlog $FileForBlog
 * @property User $User
 * @property UserGroup $UserGroup
 * @property BlogReply $BlogReply
 * @property FishForBlog $FishForBlog
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method decimal     getLat()         Returns the current record's "lat" value
 * @method decimal     getLon()         Returns the current record's "lon" value
 * @method timestamp   getDateCreate()  Returns the current record's "date_create" value
 * @method timestamp   getTs()          Returns the current record's "ts" value
 * @method string      getContent()     Returns the current record's "content" value
 * @method string      getLoc()         Returns the current record's "loc" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method string      getCaption()     Returns the current record's "caption" value
 * @method string      getKeyword()     Returns the current record's "keyword" value
 * @method timestamp   getDateBlog()    Returns the current record's "date_blog" value
 * @method integer     getSec()         Returns the current record's "sec" value
 * @method integer     getGroupId()     Returns the current record's "group_id" value
 * @method string      getUrl()         Returns the current record's "url" value
 * @method string      getUrlCaption()  Returns the current record's "url_caption" value
 * @method FileForBlog getFileForBlog() Returns the current record's "FileForBlog" value
 * @method User        getUser()        Returns the current record's "User" value
 * @method UserGroup   getUserGroup()   Returns the current record's "UserGroup" value
 * @method BlogReply   getBlogReply()   Returns the current record's "BlogReply" value
 * @method FishForBlog getFishForBlog() Returns the current record's "FishForBlog" value
 * @method Blog        setId()          Sets the current record's "id" value
 * @method Blog        setLat()         Sets the current record's "lat" value
 * @method Blog        setLon()         Sets the current record's "lon" value
 * @method Blog        setDateCreate()  Sets the current record's "date_create" value
 * @method Blog        setTs()          Sets the current record's "ts" value
 * @method Blog        setContent()     Sets the current record's "content" value
 * @method Blog        setLoc()         Sets the current record's "loc" value
 * @method Blog        setUserId()      Sets the current record's "user_id" value
 * @method Blog        setCaption()     Sets the current record's "caption" value
 * @method Blog        setKeyword()     Sets the current record's "keyword" value
 * @method Blog        setDateBlog()    Sets the current record's "date_blog" value
 * @method Blog        setSec()         Sets the current record's "sec" value
 * @method Blog        setGroupId()     Sets the current record's "group_id" value
 * @method Blog        setUrl()         Sets the current record's "url" value
 * @method Blog        setUrlCaption()  Sets the current record's "url_caption" value
 * @method Blog        setFileForBlog() Sets the current record's "FileForBlog" value
 * @method Blog        setUser()        Sets the current record's "User" value
 * @method Blog        setUserGroup()   Sets the current record's "UserGroup" value
 * @method Blog        setBlogReply()   Sets the current record's "BlogReply" value
 * @method Blog        setFishForBlog() Sets the current record's "FishForBlog" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('lat', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             'scale' => '12',
             ));
        $this->hasColumn('lon', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             'scale' => '12',
             ));
        $this->hasColumn('date_create', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('ts', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('content', 'string', 2500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2500,
             ));
        $this->hasColumn('loc', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('caption', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('keyword', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('date_blog', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('sec', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('url_caption', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FileForBlog', array(
             'local' => 'id',
             'foreign' => 'blog_id'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('UserGroup', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasOne('BlogReply', array(
             'local' => 'id',
             'foreign' => 'pid'));

        $this->hasOne('FishForBlog', array(
             'local' => 'id',
             'foreign' => 'pid'));
    }
}