<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserGroupType', 'doctrine-discuss');

/**
 * BaseUserGroupType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $description
 * @property Doctrine_Collection $UserGroup
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getUserGroup()   Returns the current record's "UserGroup" collection
 * @method UserGroupType       setId()          Sets the current record's "id" value
 * @method UserGroupType       setDescription() Sets the current record's "description" value
 * @method UserGroupType       setUserGroup()   Sets the current record's "UserGroup" collection
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserGroupType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_group_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UserGroup', array(
             'local' => 'id',
             'foreign' => 'gtype'));
    }
}