<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('County', 'doctrine');

/**
 * BaseCounty
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $county
 * @property integer $county_fips
 * @property string $state
 * @property integer $state_fips
 * @property string $class_code
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method string  getCounty()      Returns the current record's "county" value
 * @method integer getCountyFips()  Returns the current record's "county_fips" value
 * @method string  getState()       Returns the current record's "state" value
 * @method integer getStateFips()   Returns the current record's "state_fips" value
 * @method string  getClassCode()   Returns the current record's "class_code" value
 * @method County  setId()          Sets the current record's "id" value
 * @method County  setCounty()      Sets the current record's "county" value
 * @method County  setCountyFips()  Sets the current record's "county_fips" value
 * @method County  setState()       Sets the current record's "state" value
 * @method County  setStateFips()   Sets the current record's "state_fips" value
 * @method County  setClassCode()   Sets the current record's "class_code" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCounty extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('county');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('county', 'string', 125, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 125,
             ));
        $this->hasColumn('county_fips', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('state', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('state_fips', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('class_code', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 5,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}