<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LocBad', 'doctrine-geocode');

/**
 * BaseLocBad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $input
 * @property timestamp $date_create
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getInput()       Returns the current record's "input" value
 * @method timestamp getDateCreate()  Returns the current record's "date_create" value
 * @method LocBad    setId()          Sets the current record's "id" value
 * @method LocBad    setInput()       Sets the current record's "input" value
 * @method LocBad    setDateCreate()  Sets the current record's "date_create" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocBad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('loc_bad');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('input', 'string', 125, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 125,
             ));
        $this->hasColumn('date_create', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}