<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ReportForFlag', 'doctrine-discuss');

/**
 * BaseReportForFlag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $report_id
 * @property integer $user_id
 * @property integer $flag
 * @property timestamp $ts
 * 
 * @method integer       getReportId()  Returns the current record's "report_id" value
 * @method integer       getUserId()    Returns the current record's "user_id" value
 * @method integer       getFlag()      Returns the current record's "flag" value
 * @method timestamp     getTs()        Returns the current record's "ts" value
 * @method ReportForFlag setReportId()  Sets the current record's "report_id" value
 * @method ReportForFlag setUserId()    Sets the current record's "user_id" value
 * @method ReportForFlag setFlag()      Sets the current record's "flag" value
 * @method ReportForFlag setTs()        Sets the current record's "ts" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReportForFlag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('report_for_flag');
        $this->hasColumn('report_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('flag', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '5',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ts', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}