<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CatchByFishMonth', 'doctrine');

/**
 * BaseCatchByFishMonth
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $fish_id
 * @property integer $cmonth
 * @property integer $count_s3
 * @property integer $count_fish
 * @property decimal $avg_length
 * @property decimal $avg_weight
 * @property integer $rate
 * @property FishSpecies $FishSpecies
 * 
 * @method integer          getId()          Returns the current record's "id" value
 * @method integer          getFishId()      Returns the current record's "fish_id" value
 * @method integer          getCmonth()      Returns the current record's "cmonth" value
 * @method integer          getCountS3()     Returns the current record's "count_s3" value
 * @method integer          getCountFish()   Returns the current record's "count_fish" value
 * @method decimal          getAvgLength()   Returns the current record's "avg_length" value
 * @method decimal          getAvgWeight()   Returns the current record's "avg_weight" value
 * @method integer          getRate()        Returns the current record's "rate" value
 * @method FishSpecies      getFishSpecies() Returns the current record's "FishSpecies" value
 * @method CatchByFishMonth setId()          Sets the current record's "id" value
 * @method CatchByFishMonth setFishId()      Sets the current record's "fish_id" value
 * @method CatchByFishMonth setCmonth()      Sets the current record's "cmonth" value
 * @method CatchByFishMonth setCountS3()     Sets the current record's "count_s3" value
 * @method CatchByFishMonth setCountFish()   Sets the current record's "count_fish" value
 * @method CatchByFishMonth setAvgLength()   Sets the current record's "avg_length" value
 * @method CatchByFishMonth setAvgWeight()   Sets the current record's "avg_weight" value
 * @method CatchByFishMonth setRate()        Sets the current record's "rate" value
 * @method CatchByFishMonth setFishSpecies() Sets the current record's "FishSpecies" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCatchByFishMonth extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('catch_by_fish_month');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fish_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cmonth', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('count_s3', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('count_fish', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('avg_length', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '1',
             ));
        $this->hasColumn('avg_weight', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '1',
             ));
        $this->hasColumn('rate', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FishSpecies', array(
             'local' => 'fish_id',
             'foreign' => 'id'));
    }
}