<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Promo', 'doctrine-discuss');

/**
 * BasePromo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $caption
 * @property timestamp $date_create
 * @property string $subject
 * @property string $email_from
 * @property decimal $lat
 * @property decimal $lon
 * @property string $name_from
 * @property string $title_from
 * @property User $User
 * @property PromoSent $PromoSent
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getUserId()      Returns the current record's "user_id" value
 * @method string    getCaption()     Returns the current record's "caption" value
 * @method timestamp getDateCreate()  Returns the current record's "date_create" value
 * @method string    getSubject()     Returns the current record's "subject" value
 * @method string    getEmailFrom()   Returns the current record's "email_from" value
 * @method decimal   getLat()         Returns the current record's "lat" value
 * @method decimal   getLon()         Returns the current record's "lon" value
 * @method string    getNameFrom()    Returns the current record's "name_from" value
 * @method string    getTitleFrom()   Returns the current record's "title_from" value
 * @method User      getUser()        Returns the current record's "User" value
 * @method PromoSent getPromoSent()   Returns the current record's "PromoSent" value
 * @method Promo     setId()          Sets the current record's "id" value
 * @method Promo     setUserId()      Sets the current record's "user_id" value
 * @method Promo     setCaption()     Sets the current record's "caption" value
 * @method Promo     setDateCreate()  Sets the current record's "date_create" value
 * @method Promo     setSubject()     Sets the current record's "subject" value
 * @method Promo     setEmailFrom()   Sets the current record's "email_from" value
 * @method Promo     setLat()         Sets the current record's "lat" value
 * @method Promo     setLon()         Sets the current record's "lon" value
 * @method Promo     setNameFrom()    Sets the current record's "name_from" value
 * @method Promo     setTitleFrom()   Sets the current record's "title_from" value
 * @method Promo     setUser()        Sets the current record's "User" value
 * @method Promo     setPromoSent()   Sets the current record's "PromoSent" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePromo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('promo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('caption', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('date_create', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('email_from', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lat', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             'scale' => '12',
             ));
        $this->hasColumn('lon', 'decimal', 18, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 18,
             'scale' => '12',
             ));
        $this->hasColumn('name_from', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('title_from', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('PromoSent', array(
             'local' => 'id',
             'foreign' => 'pid'));
    }
}