<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FishSpecies2', 'doctrine');

/**
 * BaseFishSpecies2
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $sp_code
 * @property string $tsn
 * @property string $name_common
 * @property string $name_sci
 * @property integer $id
 * @property integer $rate
 * 
 * @method string       getSpCode()      Returns the current record's "sp_code" value
 * @method string       getTsn()         Returns the current record's "tsn" value
 * @method string       getNameCommon()  Returns the current record's "name_common" value
 * @method string       getNameSci()     Returns the current record's "name_sci" value
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getRate()        Returns the current record's "rate" value
 * @method FishSpecies2 setSpCode()      Sets the current record's "sp_code" value
 * @method FishSpecies2 setTsn()         Sets the current record's "tsn" value
 * @method FishSpecies2 setNameCommon()  Sets the current record's "name_common" value
 * @method FishSpecies2 setNameSci()     Sets the current record's "name_sci" value
 * @method FishSpecies2 setId()          Sets the current record's "id" value
 * @method FishSpecies2 setRate()        Sets the current record's "rate" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFishSpecies2 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fish_species2');
        $this->hasColumn('sp_code', 'string', 10, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('tsn', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('name_common', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('name_sci', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('rate', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}