<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PromoSent', 'doctrine-discuss');

/**
 * BasePromoSent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $date_create
 * @property integer $user_id
 * @property integer $pid
 * @property integer $promo_user_id
 * @property integer $status
 * @property string $code
 * @property User $User
 * @property Promo $Promo
 * 
 * @method integer   getId()            Returns the current record's "id" value
 * @method timestamp getDateCreate()    Returns the current record's "date_create" value
 * @method integer   getUserId()        Returns the current record's "user_id" value
 * @method integer   getPid()           Returns the current record's "pid" value
 * @method integer   getPromoUserId()   Returns the current record's "promo_user_id" value
 * @method integer   getStatus()        Returns the current record's "status" value
 * @method string    getCode()          Returns the current record's "code" value
 * @method User      getUser()          Returns the current record's "User" value
 * @method Promo     getPromo()         Returns the current record's "Promo" value
 * @method PromoSent setId()            Sets the current record's "id" value
 * @method PromoSent setDateCreate()    Sets the current record's "date_create" value
 * @method PromoSent setUserId()        Sets the current record's "user_id" value
 * @method PromoSent setPid()           Sets the current record's "pid" value
 * @method PromoSent setPromoUserId()   Sets the current record's "promo_user_id" value
 * @method PromoSent setStatus()        Sets the current record's "status" value
 * @method PromoSent setCode()          Sets the current record's "code" value
 * @method PromoSent setUser()          Sets the current record's "User" value
 * @method PromoSent setPromo()         Sets the current record's "Promo" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePromoSent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('promo_sent');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('date_create', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('promo_user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('code', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Promo', array(
             'local' => 'pid',
             'foreign' => 'id'));
    }
}