<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FishAreaX', 'doctrine');

/**
 * BaseFishAreaX
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $description
 * 
 * @method string    getId()          Returns the current record's "id" value
 * @method string    getDescription() Returns the current record's "description" value
 * @method FishAreaX setId()          Sets the current record's "id" value
 * @method FishAreaX setDescription() Sets the current record's "description" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFishAreaX extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fish_area_x');
        $this->hasColumn('id', 'string', 1, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('description', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}