<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FileForSpot', 'doctrine-discuss');

/**
 * BaseFileForSpot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $file_id
 * @property integer $pid
 * @property timestamp $ts
 * @property integer $status
 * @property Spot $Spot
 * @property File $File
 * 
 * @method integer     getFileId()  Returns the current record's "file_id" value
 * @method integer     getPid()     Returns the current record's "pid" value
 * @method timestamp   getTs()      Returns the current record's "ts" value
 * @method integer     getStatus()  Returns the current record's "status" value
 * @method Spot        getSpot()    Returns the current record's "Spot" value
 * @method File        getFile()    Returns the current record's "File" value
 * @method FileForSpot setFileId()  Sets the current record's "file_id" value
 * @method FileForSpot setPid()     Sets the current record's "pid" value
 * @method FileForSpot setTs()      Sets the current record's "ts" value
 * @method FileForSpot setStatus()  Sets the current record's "status" value
 * @method FileForSpot setSpot()    Sets the current record's "Spot" value
 * @method FileForSpot setFile()    Sets the current record's "File" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFileForSpot extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_for_spot');
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ts', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Spot', array(
             'local' => 'spot_id',
             'foreign' => 'id'));

        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id'));
    }
}