<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserReset', 'doctrine-discuss');

/**
 * BaseUserReset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $reset_code
 * @property timestamp $ts
 * @property timestamp $date_create
 * @property integer $status
 * @property integer $user_id
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method string    getResetCode()   Returns the current record's "reset_code" value
 * @method timestamp getTs()          Returns the current record's "ts" value
 * @method timestamp getDateCreate()  Returns the current record's "date_create" value
 * @method integer   getStatus()      Returns the current record's "status" value
 * @method integer   getUserId()      Returns the current record's "user_id" value
 * @method UserReset setId()          Sets the current record's "id" value
 * @method UserReset setResetCode()   Sets the current record's "reset_code" value
 * @method UserReset setTs()          Sets the current record's "ts" value
 * @method UserReset setDateCreate()  Sets the current record's "date_create" value
 * @method UserReset setStatus()      Sets the current record's "status" value
 * @method UserReset setUserId()      Sets the current record's "user_id" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserReset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_reset');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('reset_code', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('ts', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('date_create', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}