<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FishForSpot', 'doctrine-discuss');

/**
 * BaseFishForSpot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pid
 * @property integer $fish_id
 * @property integer $status
 * @property integer $count_fish
 * @property decimal $avg_length
 * @property decimal $avg_weight
 * @property Doctrine_Collection $Spot
 * @property Doctrine_Collection $Fish
 * 
 * @method integer             getPid()        Returns the current record's "pid" value
 * @method integer             getFishId()     Returns the current record's "fish_id" value
 * @method integer             getStatus()     Returns the current record's "status" value
 * @method integer             getCountFish()  Returns the current record's "count_fish" value
 * @method decimal             getAvgLength()  Returns the current record's "avg_length" value
 * @method decimal             getAvgWeight()  Returns the current record's "avg_weight" value
 * @method Doctrine_Collection getSpot()       Returns the current record's "Spot" collection
 * @method Doctrine_Collection getFish()       Returns the current record's "Fish" collection
 * @method FishForSpot         setPid()        Sets the current record's "pid" value
 * @method FishForSpot         setFishId()     Sets the current record's "fish_id" value
 * @method FishForSpot         setStatus()     Sets the current record's "status" value
 * @method FishForSpot         setCountFish()  Sets the current record's "count_fish" value
 * @method FishForSpot         setAvgLength()  Sets the current record's "avg_length" value
 * @method FishForSpot         setAvgWeight()  Sets the current record's "avg_weight" value
 * @method FishForSpot         setSpot()       Sets the current record's "Spot" collection
 * @method FishForSpot         setFish()       Sets the current record's "Fish" collection
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFishForSpot extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fish_for_spot');
        $this->hasColumn('pid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fish_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('count_fish', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('avg_length', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '1',
             ));
        $this->hasColumn('avg_weight', 'decimal', 10, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             'scale' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Spot', array(
             'local' => 'pid',
             'foreign' => 'id'));

        $this->hasMany('Fish', array(
             'local' => 'fish_id',
             'foreign' => 'id'));
    }
}