<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Subregion', 'doctrine');

/**
 * BaseSubregion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $area
 * 
 * @method integer   getId()   Returns the current record's "id" value
 * @method string    getArea() Returns the current record's "area" value
 * @method Subregion setId()   Sets the current record's "id" value
 * @method Subregion setArea() Sets the current record's "area" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubregion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subregion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('area', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}