<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FishSpecies', 'doctrine');

/**
 * BaseFishSpecies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $sp_code
 * @property string $tsn
 * @property string $name_common
 * @property string $name_sci
 * @property integer $id
 * @property integer $rate
 * @property string $wiki_title
 * @property FishNames $FishNames
 * @property Doctrine_Collection $CatchByMonth
 * @property Doctrine_Collection $CatchByFishMonth
 * 
 * @method string              getSpCode()           Returns the current record's "sp_code" value
 * @method string              getTsn()              Returns the current record's "tsn" value
 * @method string              getNameCommon()       Returns the current record's "name_common" value
 * @method string              getNameSci()          Returns the current record's "name_sci" value
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getRate()             Returns the current record's "rate" value
 * @method string              getWikiTitle()        Returns the current record's "wiki_title" value
 * @method FishNames           getFishNames()        Returns the current record's "FishNames" value
 * @method Doctrine_Collection getCatchByMonth()     Returns the current record's "CatchByMonth" collection
 * @method Doctrine_Collection getCatchByFishMonth() Returns the current record's "CatchByFishMonth" collection
 * @method FishSpecies         setSpCode()           Sets the current record's "sp_code" value
 * @method FishSpecies         setTsn()              Sets the current record's "tsn" value
 * @method FishSpecies         setNameCommon()       Sets the current record's "name_common" value
 * @method FishSpecies         setNameSci()          Sets the current record's "name_sci" value
 * @method FishSpecies         setId()               Sets the current record's "id" value
 * @method FishSpecies         setRate()             Sets the current record's "rate" value
 * @method FishSpecies         setWikiTitle()        Sets the current record's "wiki_title" value
 * @method FishSpecies         setFishNames()        Sets the current record's "FishNames" value
 * @method FishSpecies         setCatchByMonth()     Sets the current record's "CatchByMonth" collection
 * @method FishSpecies         setCatchByFishMonth() Sets the current record's "CatchByFishMonth" collection
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFishSpecies extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fish_species');
        $this->hasColumn('sp_code', 'string', 10, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('tsn', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('name_common', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('name_sci', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('rate', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('wiki_title', 'string', 500, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FishNames', array(
             'local' => 'id',
             'foreign' => 'fish_id'));

        $this->hasMany('CatchByMonth', array(
             'local' => 'id',
             'foreign' => 'fish_id'));

        $this->hasMany('CatchByFishMonth', array(
             'local' => 'id',
             'foreign' => 'fish_id'));
    }
}