<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UserForGroup', 'doctrine-discuss');

/**
 * BaseUserForGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $group_id
 * @property timestamp $ts
 * @property integer $sec
 * @property timestamp $date_create
 * @property Doctrine_Collection $User
 * @property Doctrine_Collection $UserGroup
 * 
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method integer             getGroupId()     Returns the current record's "group_id" value
 * @method timestamp           getTs()          Returns the current record's "ts" value
 * @method integer             getSec()         Returns the current record's "sec" value
 * @method timestamp           getDateCreate()  Returns the current record's "date_create" value
 * @method Doctrine_Collection getUser()        Returns the current record's "User" collection
 * @method Doctrine_Collection getUserGroup()   Returns the current record's "UserGroup" collection
 * @method UserForGroup        setUserId()      Sets the current record's "user_id" value
 * @method UserForGroup        setGroupId()     Sets the current record's "group_id" value
 * @method UserForGroup        setTs()          Sets the current record's "ts" value
 * @method UserForGroup        setSec()         Sets the current record's "sec" value
 * @method UserForGroup        setDateCreate()  Sets the current record's "date_create" value
 * @method UserForGroup        setUser()        Sets the current record's "User" collection
 * @method UserForGroup        setUserGroup()   Sets the current record's "UserGroup" collection
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserForGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_for_group');
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ts', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('sec', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('date_create', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('UserGroup', array(
             'local' => 'group_id',
             'foreign' => 'id'));
    }
}