<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FileForBlog', 'doctrine-discuss');

/**
 * BaseFileForBlog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $file_id
 * @property integer $pid
 * @property timestamp $ts
 * @property integer $status
 * @property Blog $Blog
 * @property File $File
 * 
 * @method integer     getFileId()  Returns the current record's "file_id" value
 * @method integer     getPid()     Returns the current record's "pid" value
 * @method timestamp   getTs()      Returns the current record's "ts" value
 * @method integer     getStatus()  Returns the current record's "status" value
 * @method Blog        getBlog()    Returns the current record's "Blog" value
 * @method File        getFile()    Returns the current record's "File" value
 * @method FileForBlog setFileId()  Sets the current record's "file_id" value
 * @method FileForBlog setPid()     Sets the current record's "pid" value
 * @method FileForBlog setTs()      Sets the current record's "ts" value
 * @method FileForBlog setStatus()  Sets the current record's "status" value
 * @method FileForBlog setBlog()    Sets the current record's "Blog" value
 * @method FileForBlog setFile()    Sets the current record's "File" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFileForBlog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file_for_blog');
        $this->hasColumn('file_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ts', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Blog', array(
             'local' => 'blog_id',
             'foreign' => 'id'));

        $this->hasOne('File', array(
             'local' => 'file_id',
             'foreign' => 'id'));
    }
}