<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('FishAlias', 'doctrine-discuss');

/**
 * BaseFishAlias
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $fish_id
 * @property Fish $Fish
 * 
 * @method integer   getId()      Returns the current record's "id" value
 * @method string    getName()    Returns the current record's "name" value
 * @method integer   getFishId()  Returns the current record's "fish_id" value
 * @method Fish      getFish()    Returns the current record's "Fish" value
 * @method FishAlias setId()      Sets the current record's "id" value
 * @method FishAlias setName()    Sets the current record's "name" value
 * @method FishAlias setFishId()  Sets the current record's "fish_id" value
 * @method FishAlias setFish()    Sets the current record's "Fish" value
 * 
 * @package    fb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFishAlias extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fish_alias');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('fish_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Fish', array(
             'local' => 'fish_id',
             'foreign' => 'id'));
    }
}