<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/09/25 17:44:45
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#FFFFFF',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => false,
  'library' => 'gd_mime_type',
),
  'app_servers_front' => array (
  0 => 'front1i.fishblab.com',
  1 => 'front2i.fishblab.com',
),
));
