<?php

/**
 * BlogForFlagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogForFlagTable extends Doctrine_Table{
  public static function getInstance(){
    return Doctrine_Core::getTable('BlogForFlag');
  }

  public function addBlogFlag($blog_id,$user_id,$flag){
    $blogFF = new BlogForFlag();
    $blogFF->setBlogId($blog_id);
    $blogFF->setUserId($user_id);
    $blogFF->setFlag($flag);
    $blogFF->save();
    return $blogFF;
  }

  public function updateBlogFlag($blog_id,$user_id,$flag){
    $q = Doctrine_Query::create()
      ->update('BlogForFlag b')
      ->set('flag', $flag)
      ->where('b.blog_id = ?', $blog_id)
      ->andWhere('b.user_id = ?', $user_id);
    $q->execute();
  }
  
  public function getBlogFlag($blog_id,$user_id){
    $q = Doctrine_Query::create()
      ->select('b.blog_id,b.user_id,b.flag,b.ts')
      ->from('BlogForFlag b')
      ->where('b.blog_id = ?',$blog_id)
      ->andWhere('b.user_id = ?',$user_id);
    $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
    if( count($rows) > 0){
      $row = $rows[0];
      $rec['blog_id'] = intval($row['b_blog_id']);
      $rec['user_id'] = intval($row['b_user_id']);
      $rec['flag'] = intval($row['b_flag']);
      $rec['ts'] = $row['b_ts'];
      return $rec;
    }else{
      return False;
    }
  }

}