<?php

/**
 * CatchByCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CatchByCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CatchByCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CatchByCity');
    }

    public function allCities($limit = 50){
      $q = Doctrine_Query::create()
	->select('c.state,c.city,c.count_fish,c.avg_weight,c.avg_length')
	->from('CatchByCity c')
	->orderBy('count_fish DESC')
	->limit($limit);
      $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
      $ret = array();
      foreach($rows as $i => $row){
	$ret[$i]['state'] = $row['c_state'];
	$ret[$i]['city'] = $row['c_city'];
	$ret[$i]['count'] = intval($row['c_count_fish']);
	$ret[$i]['avg_weight'] = intval($row['c_avg_weight']);
	$ret[$i]['avg_length'] = intval($row['c_avg_length']);
	$ret[$i]['class'] = 'tc5';
      }
      return $ret;
    }    

}