<?php

/**
 * CatchBySiteCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CatchBySiteCityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CatchBySiteCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CatchBySiteCity');
    }

    public function catchBySiteCity($state,$city){
      $q = Doctrine_Query::create()
	->select('c.site_id,c.name,c.city,c.state,c.count_fish,c.avg_weight,c.avg_length,c.lat,c.lon')
	->from('CatchBySiteCity c')
	->where('c.state = ?',$state)
	->andWhere('c.city = ?',$city);
      $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
      $ret = array();
      foreach($rows as $i => $row){
	$ret[$i]['site_id'] = $row['c_site_id'];
	$ret[$i]['name'] = $row['c_name'];
	$ret[$i]['city'] = $row['c_city'];
	$ret[$i]['state'] = $row['c_state'];
	$ret[$i]['count'] = intval($row['c_count_fish']);
	$ret[$i]['avg_weight'] = intval($row['c_avg_weight']);
	$ret[$i]['avg_length'] = intval($row['c_avg_length']);
	$ret[$i]['lat'] = floatval($row['c_lat']);
	$ret[$i]['lon'] = floatval($row['c_lon']);
	$ret[$i]['class'] = 'tc5';
      }
      return $ret;
    }    

    public function catchBySiteState($state,$limit = 50){
      $q = Doctrine_Query::create()
	->select('c.site_id,c.name,c.city,c.state,c.count_fish,c.avg_weight,c.avg_length,c.lat,c.lon')
	->from('CatchBySiteCity c')
	->where('c.state = ?',$state)
	->limit($limit);
      $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
      $ret = array();
      foreach($rows as $i => $row){
	$ret[$i]['site_id'] = $row['c_site_id'];
	$ret[$i]['name'] = $row['c_name'];
	$ret[$i]['city'] = $row['c_city'];
	$ret[$i]['state'] = $row['c_state'];
	$ret[$i]['count'] = intval($row['c_count_fish']);
	$ret[$i]['avg_weight'] = intval($row['c_avg_weight']);
	$ret[$i]['avg_length'] = intval($row['c_avg_length']);
	$ret[$i]['lat'] = floatval($row['c_lat']);
	$ret[$i]['lon'] = floatval($row['c_lon']);
	$ret[$i]['class'] = 'tc5';
      }
      return $ret;
    }    

    public function catchBySite($state,$city,$site){
      $q = Doctrine_Query::create()
	->select('c.site_id,c.name,c.city,c.state,c.count_fish,c.avg_weight,c.avg_length,c.lat,c.lon')
	->from('CatchBySiteCity c')
	->where('c.state = ?',$state)
	->andWhere('c.city = ?',$city)
	->andWhere('c.name = ?',$site);
      $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
      $row = $rows[0];
      $ret = array();
      $ret['site_id'] = $row['c_site_id'];
      $ret['name'] = $row['c_name'];
      $ret['city'] = $row['c_city'];
      $ret['state'] = $row['c_state'];
      $ret['count'] = intval($row['c_count_fish']);
      $ret['avg_weight'] = intval($row['c_avg_weight']);
      $ret['avg_length'] = intval($row['c_avg_length']);
      $ret['lat'] = floatval($row['c_lat']);
      $ret['lon'] = floatval($row['c_lon']);
      $ret['class'] = 'tc5';
      return $ret;
    }    

}