<?php

/**
 * CatchByFishMonthTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CatchByFishMonthTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CatchByFishMonthTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CatchByFishMonth');
    }
    # catch query by fish/month, grouped by fish
    public function catchByFish($fish_id,$month_range){
      $q = Doctrine_Query::create()
	->select('c.fish_id,SUM(c.count_fish) AS count_fish,FORMAT(AVG(c.avg_length),1) AS avg_length,FORMAT(AVG(c.avg_weight),1) AS avg_weight,f.name_common AS name,f.name_sci AS name_sci')
	->from('CatchByFishMonth c')
	->innerJoin('c.FishSpecies f')
	->where('c.fish_id = ?', $fish_id)
	->andWhere('c.cmonth >= ? AND c.cmonth <= ?', $month_range)
	->groupBy('c.fish_id');
      $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
      $ret = array('fish_id' => False);
      if($row = $rows[0]){
	$ret['fish_id'] = intval($row['c_fish_id']);
	$ret['name'] = $row['f_name'];
	$ret['name_sci'] = $row['f_name_sci'];
	$ret['count'] = intval($row['c_count_fish']);
	$ret['avg_weight'] = ($row['c_avg_weight'] ? $row['c_avg_weight'] : '');
	$ret['avg_length'] = ($row['c_avg_length'] ? $row['c_avg_length'] : '');
      }
      return $ret;
    }

    # catch query by <optional> month grouped by fish/month
    public function catchByFishMonth($month_range = array(1,12),$limit = 100){
      $q = Doctrine_Query::create()
	->select('c.fish_id,c.cmonth,c.count_fish,c.avg_length,c.avg_weight,f.rate,f.name_common')
	->from('CatchByFishMonth c')
	->innerJoin('c.FishSpecies f')
	->andWhere('c.cmonth >= ? AND c.cmonth <= ?', $month_range)
	->orderBy('c.rate DESC,c.count_fish DESC')
	->limit($limit);
      $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
      $ret = array();
      foreach($rows as $i => $row){
	$ret[$i]['fish_id'] = intval($row['c_fish_id']);
	$ret[$i]['month'] = intval($row['c_cmonth']);
	$ret[$i]['name'] = $row['f_name_common'];
	$ret[$i]['count'] = intval($row['c_count_fish']);
	$ret[$i]['rate'] = intval($row['f_rate']);
	$ret[$i]['avg_weight'] = ($row['c_avg_weight'] ? $row['c_avg_weight'] : '');
	$ret[$i]['avg_length'] = ($row['c_avg_length'] ? $row['c_avg_length'] : '');
      }
      return $ret;
    }

    # catch query by <optional> month grouped by fish/month
    public function catchByAllFish($months = array(1,12),$limit = 10){
      $q = Doctrine_Query::create()
	->select('c.fish_id,SUM(c.count_fish) AS count_fish,FORMAT(AVG(c.avg_length),1) AS avg_length,FORMAT(AVG(c.avg_weight),1) AS avg_weight,f.rate,f.name_common')
	->select('c.fish_id,c.cmonth,c.count_fish,c.avg_length,c.avg_weight,f.rate,f.name_common')
	->from('CatchByFishMonth c')
	->innerJoin('c.FishSpecies f')
	->where('c.cmonth >= ? AND c.cmonth <= ?', $months)
	->groupBy('c.fish_id')
	->orderBy('c.count_fish DESC')
	->limit($limit);
#	->orderBy('f.rate DESC,c.count_fish DESC')
      $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
      $ret = array();
      foreach($rows as $i => $row){
	$ret[$i]['fish_id'] = intval($row['c_fish_id']);
	$ret[$i]['month'] = intval($row['c_cmonth']);
	$ret[$i]['name'] = $row['f_name_common'];
	$ret[$i]['count'] = intval($row['c_count_fish']);
	$ret[$i]['rate'] = intval($row['f_rate']);
	$ret[$i]['avg_weight'] = ($row['c_avg_weight'] ? $row['c_avg_weight'] : '');
	$ret[$i]['avg_length'] = ($row['c_avg_length'] ? $row['c_avg_length'] : '');
      }
      return $ret;
    }

    public function catchByFishAnnual($fish_id){
      $q = Doctrine_Query::create()
	->select('c.cmonth AS month,c.count_fish,c.fish_id,f.name_common AS name')
	->from('CatchByFishMonth c')
	->innerJoin('c.FishSpecies f')
	->where('c.fish_id = ?', $fish_id)
	->groupBy('c.fish_id')
	->addGroupBy('c.cmonth')
	->limit(20);
      $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
      $json = array();
      foreach($rows as $i => $row){
	$json[$i]['fish_id'] = intval($row['c_fish_id']);
	$json[$i]['name'] = $row['f_name'];
	$json[$i]['month'] = $row['c_month'];
	$json[$i]['count'] = intval($row['c_count_fish']);
      }
      return $json;
    }

}