<?php

/**
 * CatchByFishSiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CatchByFishSiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CatchByFishSiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CatchByFishSite');
    }

    public function fishBySite($site_id,$limit = 50){
      $q = Doctrine_Query::create()
	->select('c.count_fish,c.fish_id,c.name,c.name_sci,c.rate,c.count_fish,c.avg_weight,c.avg_length')
	->from('CatchByFishSite c')
	->where('c.site_id = ?',$site_id)
	->orderBy('count_fish DESC')
	->limit($limit);
      $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
      $ret = array();
      foreach($rows as $i => $row){
	$ret[$i]['fish_id'] = intval($row['c_fish_id']);
	$ret[$i]['name'] = $row['c_name'];
	$ret[$i]['name_sci'] = $row['c_name_sci'];
	$ret[$i]['count'] = intval($row['c_count_fish']);
	$ret[$i]['rate'] = intval($row['c_rate']);
	$ret[$i]['class'] = 'tc5';
      }
      return $ret;
    }    

}