<?php

/**
 * DiscForFlagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiscForFlagTable extends Doctrine_Table
{
  public static function getInstance(){
    return Doctrine_Core::getTable('DiscForFlag');
  }
  
  public function addDiscFlag($disc_id,$user_id,$flag){
    $discFF = new DiscForFlag();
    $discFF->setDiscId($disc_id);
    $discFF->setUserId($user_id);
    $discFF->setFlag($flag);
    $discFF->save();
    return $discFF;
  }

  public function updateDiscFlag($disc_id,$user_id,$flag){
    $q = Doctrine_Query::create()
      ->update('DiscForFlag d')
      ->set('flag', $flag)
      ->where('d.disc_id = ?', $disc_id)
      ->andWhere('d.user_id = ?', $user_id);
    $q->execute();
  }
  
  public function getDiscFlag($disc_id,$user_id){
    $q = Doctrine_Query::create()
      ->select('d.disc_id,d.user_id,d.flag,d.ts')
      ->from('DiscForFlag d')
      ->where('d.disc_id = ?',$disc_id)
      ->andWhere('d.user_id = ?',$user_id);
    $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
    if( count($rows) > 0){
      $row = $rows[0];
      $rec['disc_id'] = intval($row['d_disc_id']);
      $rec['user_id'] = intval($row['d_user_id']);
      $rec['flag'] = intval($row['d_flag']);
      $rec['ts'] = $row['d_ts'];
      return $rec;
    }else{
      return False;
    }
  }

}