<?php

/**
 * FeedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeedTable extends Doctrine_Table{

  public static function getInstance(){
    return Doctrine_Core::getTable('Feed');
  }
  
  public function addFeed($p){
    $msg = $p['msg'];
    $msg = strip_tags($msg);
    $msg = trim($msg);
    if($msg and (strlen($msg) > 1) ){
      $feed = new Feed;
      $feed->setContent($msg);
      $feed->setDateCreate(new Doctrine_Expression('NOW()'));
      $feed->setSessionId($p['session_id']);
      $feed->setIp($p['ip']);
      if($p['user_id']){
	$feed->setUserId($p['user_id']);
      }
      $feed->save();
      $feed_id = $feed->getId();
      return $this->getFeed($feed_id);
    }
    return False;
  }
  
  public function getFeed($feed_id){
    $q = Doctrine_Query::create()
      ->select('id,content,DATE_FORMAT(date_create,\'%c/%e/%y\') AS date_create')
      ->from('Feed f')
      ->where('f.id = ?', $feed_id);
    $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
    if(count($rows) > 0 ){
      $rec = array();
      $rec['id'] = $rows[0]['f_id'];
      $rec['content'] = $rows[0]['f_content'];
      $rec['date_create'] = $rows[0]['f_date_create'];
      return $rec;
    }
    return False;
  }
  
}