<?php

/**
 * FileForFlagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FileForFlagTable extends Doctrine_Table{
  public static function getInstance(){
    return Doctrine_Core::getTable('FileForFlag');
  }

  public function addFileFlag($file_id,$user_id,$flag){
    $fileFF = new FileForFlag();
    $fileFF->setFileId($file_id);
    $fileFF->setUserId($user_id);
    $fileFF->setFlag($flag);
    $fileFF->save();
    return $fileFF;
  }

  public function updateFileFlag($file_id,$user_id,$flag){
    $q = Doctrine_Query::create()
      ->update('FileForFlag b')
      ->set('flag', $flag)
      ->where('b.file_id = ?', $file_id)
      ->andWhere('b.user_id = ?', $user_id);
    $q->execute();
  }
  
  public function getFileFlag($file_id,$user_id){
    $q = Doctrine_Query::create()
      ->select('b.file_id,b.user_id,b.flag,b.ts')
      ->from('FileForFlag b')
      ->where('b.file_id = ?',$file_id)
      ->andWhere('b.user_id = ?',$user_id);
    $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
    if( count($rows) > 0){
      $row = $rows[0];
      $rec['file_id'] = intval($row['b_file_id']);
      $rec['user_id'] = intval($row['b_user_id']);
      $rec['flag'] = intval($row['b_flag']);
      $rec['ts'] = $row['b_ts'];
      return $rec;
    }else{
      return False;
    }
  }

}