<?php

/**
 * FishSpecies2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FishSpecies2Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FishSpecies2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FishSpecies2');
    }
}