<?php

/**
 * FishAliasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FishAliasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FishAliasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FishAlias');
    }
}