<?php

/**
 * ReportForFlagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReportForFlagTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object ReportForFlagTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('ReportForFlag');
  }
  
  public function addReportFlag($report_id,$user_id,$flag){
    $repFF = new ReportForFlag();
    $repFF->setReportId($report_id);
    $repFF->setUserId($user_id);
    $repFF->setFlag($flag);
    $repFF->save();
    return $repFF;
  }

  public function updateReportFlag($report_id,$user_id,$flag){
    $q = Doctrine_Query::create()
      ->update('ReportForFlag r')
      ->set('flag', $flag)
      ->where('report_id = ?', $report_id)
      ->andWhere('user_id = ?', $user_id);
    $q->execute();
  }
  
  public function getReportFlag($report_id,$user_id){
    $q = Doctrine_Query::create()
      ->select('r.report_id,r.user_id,r.flag,r.ts')
      ->from('ReportForFlag r')
      ->where('r.report_id = ?',$report_id)
      ->andWhere('r.user_id = ?',$user_id);
    $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
    if( count($rows) > 0){
      $row = $rows[0];
      $rec['report_id'] = intval($row['r_report_id']);
      $rec['user_id'] = intval($row['r_user_id']);
      $rec['flag'] = intval($row['r_flag']);
      $rec['ts'] = $row['r_ts'];
      return $rec;
    }else{
      return False;
    }
  }

}