<?php

/**
 * SpotForFlagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpotForFlagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpotForFlagTable
     */
  public static function getInstance(){
    return Doctrine_Core::getTable('SpotForFlag');
  }

  public function addSpotFlag($spot_id,$user_id,$flag){
    $spotFF = new SpotForFlag();
    $spotFF->setSpotId($spot_id);
    $spotFF->setUserId($user_id);
    $spotFF->setFlag($flag);
    $spotFF->save();
    return $spotFF;
  }

  public function updateSpotFlag($spot_id,$user_id,$flag){
    $q = Doctrine_Query::create()
      ->update('SpotForFlag s')
      ->set('flag', $flag)
      ->where('s.spot_id = ?', $spot_id)
      ->andWhere('s.user_id = ?', $user_id);
    $q->execute();
  }
  
  public function getSpotFlag($spot_id,$user_id){
    $q = Doctrine_Query::create()
      ->select('s.spot_id,s.user_id,s.flag,s.ts')
      ->from('SpotForFlag s')
      ->where('s.spot_id = ?',$spot_id)
      ->andWhere('s.user_id = ?',$user_id);
    $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
    if( count($rows) > 0){
      $row = $rows[0];
      $rec['spot_id'] = intval($row['s_spot_id']);
      $rec['user_id'] = intval($row['s_user_id']);
      $rec['flag'] = intval($row['s_flag']);
      $rec['ts'] = $row['s_ts'];
      return $rec;
    }else{
      return False;
    }
  }

}