<?php

/**
 * UserGroupTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserGroupTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserGroupTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserGroupType');
    }
}