<?php

/**
 * UserMsgTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserMsgTable extends Doctrine_Table{
  public static function getInstance(){
    return Doctrine_Core::getTable('UserMsg');
  }
  
  public function addMsg($param){
    $mtype = ($param['mtype'] ? $param['mtype'] : 10);
    $msg = new UserMsg();
    $msg->setUserId($param['user_to_id']);
    $msg->setFromUserId($param['user_from_id']);
    $msg->setMtype($param['mtype']);
    $msg->setDateCreate(new Doctrine_Expression('NOW()'));
    $msg->save;
  }
}