<?php

/**
 * UserForFriendBlockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserForFriendBlockTable extends Doctrine_Table{
  public static function getInstance(){
    return Doctrine_Core::getTable('UserForFriendBlock');
  }
  
  public function addBlock($user_id,$friend_id){
    $ub = new UserForFriendBlock();
    $ub->setUserId($user_id);
    $ub->setFriendId($friend_id);
    $ub->save();
    return True;
  }

  public function getBlock($user_id,$friend_id){
    $q = Doctrine_Query::create()
      ->select('user_id,friend_id,ts')
      ->from('UserForFriendBlock ub')
      ->where('ub.user_id = ?', $user_id)
      ->andWhere('ub.friend_id = ?', $friend_id);
    $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
    if($rows and (count($rows) > 0) ){
      return True;
    }
    return False;
  }

  public function delBlock($user_id,$friend_id){
    $q = Doctrine_Query::create()
      ->delete()
      ->from('UserForFriendBlock ub')
      ->where('ub.user_id = ?', $user_id)
      ->andWhere('ub.friend_id = ?', $friend_id);
    $status = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
    if($status){
      return True;
    }
    return False;
  }

}