<?php

/**
 * UserForFriendReqTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserForFriendReqTable extends Doctrine_Table{

  public static function getInstance(){
    return Doctrine_Core::getTable('UserForFriendReq');
  }

  public function addRequest($user_id,$friend_id,$note){
    $uff = new UserForFriendReq();
    $uff->setUserId($user_id);
    $uff->setFriendId($friend_id);
    $note = strip_tags($note);
    $note = trim($note);
    if($note){
      $uff->setNote($note);
    }
    $uff->save();
    return True;
  }

  public function getRequest($user_id,$friend_id){
    $q = Doctrine_Query::create()
      ->select('user_id,friend_id,ts')
      ->from('UserForFriendReq u')
      ->where('u.user_id = ?', $user_id)
      ->andWhere('u.friend_id = ?', $friend_id);
    $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
    if($rows and (count($rows) > 0) ){
      return $rows[0];
    }
    return False;
  }

  public function hasRequest($user_id,$friend_id){
    $q = Doctrine_Query::create()
      ->select('user_id,friend_id,ts')
      ->from('UserForFriendReq u')
      ->where('u.user_id = ?', $user_id)
      ->andWhere('u.friend_id = ?', $friend_id);
    $rows = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
    if($rows and (count($rows) > 0) ){
      return True;
    }
    return False;
  }

  public function delRequest($user_id,$friend_id){
    $q = Doctrine_Query::create()
      ->delete()
      ->from('UserForFriendReq u')
      ->where('u.user_id = ?', $user_id)
      ->andWhere('u.friend_id = ?', $friend_id);
    $status = $q->execute(array(),Doctrine_Core::HYDRATE_SCALAR);
    if($status){
      return True;
    }
    return False;
  }
  
}