# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

all:
  metas:
    title:         FishBlab Photos
    description:   View Fishing Photos
    keywords:      Fishing photos,fish photo,fishing pictures
    #language:     en
    #robots:       index, follow
    viewport:      'initial-scale=1.0, user-scalable=no'

  stylesheets:    []
  javascripts:    []

  has_layout:     true
  layout:         layout_pano
